import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { AuthButtons } from "@/components/auth-buttons";
import { Providers } from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <header className="w-full border-b">
            <div className="max-w-5xl mx-auto p-4 flex justify-between items-center">
              <Link className="font-semibold" href="/">
                Career Buddy
              </Link>
              <AuthButtons />
            </div>
          </header>
          <main className="max-w-5xl mx-auto w-full">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
